default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tmp/development.sqlite3

test:
  <<: *default
  database: tmp/test.sqlite3

production:
  <<: *default
  database: tmp/production.sqlite3
